---
server:
    install: '1'
    packages: [vim, git, htop, npm, imagemagick]
    timezone: UTC
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.86, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant/nowhere_old
    servername: nowhere.vb
mysql:
    install: '1'
    root_password: root
    database: db
    user: user
    password: password
    dump: db/gn_redacted.sql
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php-pear, php5-imagick, php5-common, php5-mysql, php5-xdebug, php5-cgi]
xdebug:
    install: '1'
composer:
    install: '1'

